### PR TITLE
Add v hbb e iso dec27 94 x

### PR DESCRIPTION
**Pull request by capalmer85**

### CODE REVIEW

**Comment by lsoffi** [comment]
@michelif @fcouderc  Hi Chris, we are working on merging this PR. We solved a small conflict in the TnP code but when trying to test it running before the merge, we are getting the following error:
[soffi@lxplus088 TnPTreeProducer]$ cmsRun python/TnPTreeProducer_cfg.py doEleID=True isMC=False maxEvents=50
----- Begin Fatal Exception 08-Jan-2018 14:00:50 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named python/TnPTreeProducer_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named egmGedGsfElectronMiniIsolation_cfi
----- End Fatal Exception -------------------------------------------------

This is because in the 9-4-0-pre3 CMSSW release the following cfi are missing:

python/egmElectronMiniIsoModules_cff.py:    from RecoEgamma.EgammaIsolationAlgos.egmGedGsfElectronMiniIsolation_cfi import egmGedGsfElectronMiniNoPileUpIsolation
python/egmElectronMiniIsoModules_cff.py:    from RecoEgamma.EgammaIsolationAlgos.egmGedGsfElectronMiniIsolation_cfi import egmGedGsfElectronEffAreaMiniIsolation

Do you have them in a private release? 
Thanks
Livia && Francesco

**Comment by capalmer85** [comment]
Hi Livia,

That file (RecoEgamma/EgammaIsolationAlgos/python/egmGedGsfElectronMiniIsolation_cfi.py) isn't part of this package.  Since they are part of the CMSSW package, I assume that they have to be included by a cms-merge from a different branch.  I just started from your branch and added the tree branches I needed on top of that.  (It worked in 941.) 

I was just looking for this file and I don't actually find it in any 9_4_X or 10_0_X branches.   Do you know where this file comes from?  (I didn't make it.)

Cheers,
Chris

**Comment by lsoffi** [comment]
@fcouderc  @michelif  Hi Chris,

indeed they are not in 94x. In which release did you test your TnP branch? Did it work for you the test with the cmsRun?

Thanks

Livia

**Comment by capalmer85** [comment]
I didn't test it with cmsRun.  The only two lines that I actually added were:

el_sumPUPt       = cms.string("pfIsolationVariables().sumPUPt"),
el_reliso03      = cms.string("(pfIsolationVariables().sumChargedHadronPt + max(pfIsolationVariables().sumNeutralHadronEt + pfIsolationVariables().sumPhotonEt - 0.5 * pfIsolationVariables().sumPUPt,0.0)) / pt() "),

in python/egmTreesContent_cff.py.  I copied these from an area that was working and tested.

**Comment by capalmer85** [comment]
Hi Livia,

Thanks for pointing me to the instructions for testing.
Unfortunately, something is broken without my additions.  Below is the
prescription I followed:

 1130  09/01/18 19:26:39 cmsrel CMSSW_9_4_0
 1131  09/01/18 19:28:01 cd CMSSW_9_4_0/src/
 1132  09/01/18 19:28:03 cmsenv
 1133  09/01/18 19:28:08 git cms-init
 1134  09/01/18 19:29:52 git cms-merge-topic lsoffi:CMSSW_9_4_0_pre3_TnP
 1135  09/01/18 19:31:39 cd $CMSSW_BASE/src
 1136  09/01/18 19:31:39 git clone -b v2017.12.14_94X_prelim
https://github.com/lsoffi/EgammaAnalysis-TnPTreeProducer.git
EgammaAnalysis/TnPTreeProducer
 1137  09/01/18 19:31:40 scram b -j8

This ended in a compiler error:

Compiling src/EgammaAnalysis/TnPTreeProducer/python/etc/tnpInputTestFiles_cff.py
...
Sorry: IndentationError: unexpected indent (tnpInputTestFiles_cff.py, line 1)
config/SCRAM/GMake/Makefile.rules:2296: recipe for target 'CompilePython' failed
gmake[1]: *** [CompilePython] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: Leaving directory
'/afs/cern.ch/work/c/capalmer/private/hbb/2018/Q1/ElectonEfficiencies/CheckJan9/CMSSW_9_4_0'

There is an extra space at the very start of
EgammaAnalysis/TnPTreeProducer/python/etc/tnpInputTestFiles_cff.py
that must be removed.  It then compiles.  The test is tried is:

 1140  09/01/18 19:46:18 cd EgammaAnalysis/TnPTreeProducer/
 1141  09/01/18 19:46:28 cmsRun python/TnPTreeProducer_cfg.py
doEleID=True isMC=False maxEvents=5000

This gives a lengthy seg fault that I've pasted below.  The same thing
happens if I try to run in 940pre3.  Am I doing something wrong?

Cheers,
Chris




Begin processing the 1st record. Run 299368, Event 22867388,
LumiSection 61 at 09-Jan-2018 19:47:26.655 CET
Begin processing the 1001st record. Run 299368, Event 22346503,
LumiSection 61 at 09-Jan-2018 19:47:34.019 CET
Begin processing the 2001st record. Run 299368, Event 23484462,
LumiSection 61 at 09-Jan-2018 19:47:37.372 CET
Begin processing the 3001st record. Run 299368, Event 22163223,
LumiSection 61 at 09-Jan-2018 19:47:41.714 CET

A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Thread 7 (Thread 0x7f957dee9700 (LWP 27442)):
#0  0x00007f959aef6419 in syscall () from /lib64/libc.so.6
#1  0x00007f959720b86f in XrdSys::LinuxSemaphore::Wait
(this=0x7f9581352a28) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get
(this=0x7f95873779d8) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f95873779c0) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f959720ba29 in RunRunnerThread (arg=<optimized out>) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f959b1acaa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f959aef9bcd in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7f957e8ea700 (LWP 27441)):
#0  0x00007f959aef6419 in syscall () from /lib64/libc.so.6
#1  0x00007f959720b86f in XrdSys::LinuxSemaphore::Wait
(this=0x7f9581352a28) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get
(this=0x7f95873779d8) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f95873779c0) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f959720ba29 in RunRunnerThread (arg=<optimized out>) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f959b1acaa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f959aef9bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f957f2eb700 (LWP 27440)):
#0  0x00007f959aef6419 in syscall () from /lib64/libc.so.6
#1  0x00007f959720b86f in XrdSys::LinuxSemaphore::Wait
(this=0x7f9581352a28) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get
(this=0x7f95873779d8) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f95873779c0) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f959720ba29 in RunRunnerThread (arg=<optimized out>) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f959b1acaa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f959aef9bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f957fcec700 (LWP 27439)):
#0  0x00007f959b1b400d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007f9597050753 in XrdSysTimer::Wait (mills=<optimized out>) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdSys/XrdSysTimer.cc:239
#2  0x00007f95971b05f7 in XrdCl::TaskManager::RunTasks
(this=0x7f9584189f80) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdCl/XrdClTaskManager.cc:244
#3  0x00007f95971b0749 in RunRunnerThread (arg=<optimized out>) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdCl/XrdClTaskManager.cc:37
#4  0x00007f959b1acaa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f959aef9bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f95806ed700 (LWP 27438)):
#0  0x00007f959aefa1c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f9597055804 in XrdSys::IOEvents::PollE::Begin
(this=0x7f9587377aa0, syncsem=<optimized out>, retcode=<optimized
out>, eTxt=<optimized out>) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/./XrdSys/XrdSysIOEventsPollE.icc:213
#2  0x00007f9597051e75 in XrdSys::IOEvents::BootStrap::Start
(parg=0x7fff64a63420) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdSys/XrdSysIOEvents.cc:131
#3  0x00007f959704ff78 in XrdSysThread_Xeq (myargs=0x7f9580b86ce0) at
/build/cmsbld/auto-builds/CMSSW_9_4_0_pre1-slc6_amd64_gcc630/build/CMSSW_9_4_0_pre1-build/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-fmblme/xrootd-4.6.1/src/XrdSys/XrdSysPthread.cc:86
#4  0x00007f959b1acaa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f959aef9bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f9589dbf700 (LWP 27329)):
#0  0x00007f959b1b437d in waitpid () from /lib64/libpthread.so.0
#1  0x00007f9596d86637 in edm::service::cmssw_stacktrace_fork() ()
from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007f9596d86bd5 in
edm::service::InitRootHandlers::stacktraceHelperThread() () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007f959b718c2f in std::execute_native_thread_routine
(__p=0x7f9597af9970) at
../../../../../libstdc++-v3/src/c++11/thread.cc:83
#4  0x00007f959b1acaa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f959aef9bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f95995eec20 (LWP 27264)):
#0  0x00007f959aef0383 in poll () from /lib64/libc.so.6
#1  0x00007f9596d86a24 in full_read.constprop () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007f9596d871fa in
edm::service::InitRootHandlers::stacktraceFromThread() () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007f9596d88255 in sig_dostack_then_abort () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  __cxxabiv1::__dynamic_cast (src_ptr=0x0, src_type=0x7f95973bccf0
<typeinfo for edm::reftobase::BaseHolder<reco::Candidate>>,
dst_type=0x7f95973bcd18 <typeinfo for
edm::reftobase::IndirectHolder<reco::Candidate>>, src2dst=0) at
../../../../libstdc++-v3/libsupc++/dyncast.cc:50
#6  0x00007f95973a8cbc in
edm::reftobase::IndirectHolder<reco::Candidate>::isEqualTo(edm::reftobase::BaseHolder<reco::Candidate>
const&) const () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/pluginCommonToolsToolsUtilAlgos_plugins.so
#7  0x00007f9562bce101 in
tnp::TagProbePairMaker::arbitrate(std::vector<tnp::TagProbePair,
std::allocator<tnp::TagProbePair> >&) const () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libPhysicsToolsTagAndProbe.so
#8  0x00007f9562bcfda6 in tnp::TagProbePairMaker::run(edm::Event
const&) const () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libPhysicsToolsTagAndProbe.so
#9  0x00007f9560e04354 in TagProbeFitTreeProducer::analyze(edm::Event
const&, edm::EventSetup const&) () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/pluginPhysicsToolsTagAndProbe_plugins.so
#10 0x00007f959d884f82 in edm::EDAnalyzer::doEvent(edm::EventPrincipal
const&, edm::EventSetup const&, edm::ActivityRegistry*,
edm::ModuleCallingContext const*) () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#11 0x00007f959d879d62 in
edm::WorkerT<edm::EDAnalyzer>::implDo(edm::EventPrincipal const&,
edm::EventSetup const&, edm::ModuleCallingContext const*) () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#12 0x00007f959d86af17 in decltype ({parm#1}())
edm::convertException::wrap<bool
edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&,
edm::StreamID, edm::ParentContext const&,
edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool
edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&,
edm::StreamID, edm::ParentContext const&,
edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#13 0x00007f959d86b0eb in bool
edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&,
edm::StreamID, edm::ParentContext const&,
edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>::Context const*) () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#14 0x00007f959d86c58b in std::__exception_ptr::exception_ptr
edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr
const*, edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&,
edm::StreamID, edm::ParentContext const&,
edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>::Context const*) () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#15 0x00007f959d86d787 in void
edm::SerialTaskQueueChain::actionToRun<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>
>::execute()::{lambda()#1}>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1> >::execute()::{lambda()#1} const&) () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#16 0x00007f959d86d8a1 in edm::SerialTaskQueue::QueuedTask<void
edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1>
>::execute()::{lambda()#1}>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal,
(edm::BranchActionType)1> >::execute()::{lambda()#1}
const&)::{lambda()#1}>::execute() () from
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#17 0x00007f959c4a422c in
tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all
(this=0x7f9598617000, parent=..., child=<optimized out>) at
../../src/tbb/custom_scheduler.h:509
#18 0x00007f959d90829c in edm::EventProcessor::readAndProcessEvents()
() from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#19 0x00007f959d912f61 in edm::EventProcessor::runToCompletion() ()
from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#20 0x000000000040e7e2 in main::{lambda()#1}::operator()() const ()
#21 0x000000000040d19a in main ()

Current Modules:
Module: TagProbeFitTreeProducer:tnpEleIDs (crashed)

A fatal system signal has occurred: segmentation violation
Segmentation fault (core dumped)

**Comment by lsoffi** [comment]
Hi Chris, 
let me have a look. 
Thanks
Livia

**Comment by fcouderc** [comment]
@lsoffi 
the MiniIso was added by Saranya ( @saghosh )
Could you check with him if this is the problem ? I thought it was working though.
May be some files were missing.

Fabrice

**Comment by lsoffi** [comment]
Hi @capalmer85 , 
i checked the instructions and fixed the extra space.
The problem is not in the code, but there are few problematic events where the code crashes. Indeed if you test on another file you can run over 5k events w/o problems. I am investigating what is the problem in these events (potentially no pairs of Tag and Probe are found), but for the moment you can test your branch on 3k events, or use another file. I`ll add here an update once i figure out the solution. Best
Livia

**Comment by capalmer85** [comment]
Hi Livia,

I tested simply adding my two lines on top of the standard prescription,
running 3000 events, and that works fine with expected output.  This is
what I did in my original PR:
https://github.com/lsoffi/EgammaAnalysis-TnPTreeProducer/pull/1/commits/e93be0449d3ca0b9cf368020808a7738dc46c511

I'm not sure about what is going on with any other files, but I can say for
sure that I didn't make those commits.

Do you want me to make a new PR on top of a particular branch?  I went ahead and made that branch in case you want it:
https://github.com/capalmer85/EgammaAnalysis-TnPTreeProducer/tree/addVHbbEIsoDec18_try2_Jan10

Cheers,
Chris

**Comment by lsoffi** [comment]
Hi Chris, thanks. Meanwhile we fixed the isse with the crash. I will update it and try again your merge in the next hours.
Best
Livia

**Comment by lsoffi** [comment]
I close this PR b/c the fix has been implemented and committed already.

**Pull request closed without merging**
